# Altivec Intelligence - CURLmac (Mac)
APP_NAME = CURLmac
SOURCES = main.m DownloadWindowController.m
INFO_PLIST = Info.plist

LIBCURL_REQUIRED = 1
LIBCURL_LINKAGE = dynamic

# Import common Mac build engine
include /altivec/altivec_common_mac.mk
