# Altivec Intelligence - CURLmac (Mac)
APP_NAME = CURLmac
SOURCES = main.m DownloadWindowController.m

ALTIVECCORE_REQUIRED = 1
ALTIVECCORE_LINKAGE = dynamic
ALTIVECCOCOA_REQUIRED = 1
ALTIVECCOCOA_LINKAGE = dynamic

# Import common Mac build engine
include /altivec/altivec_common_mac.mk
