services:
  altivec:
    build:
      context: .
      dockerfile: Containerfile
      target: ghcr-action
    image: altivec-image
    working_dir: /repo/altivec
    volumes:
      - ~/.altivec:/root
      - .:/repo/altivec
      # Uncomment to add more tools into the container
      # ../extras:/repo/extras
      
  altivec-intelligence:
    build:
      context: .
      dockerfile: Containerfile
      target: ghcr-action
    image: altivec-intelligence-image
    stdin_open: true
    tty: true
    environment:
      - IS_SANDBOX=1
    working_dir: /repo/altivec
    volumes:
      - ~/.altivec:/root
      - .:/repo/altivec
      # Uncomment to add more tools into the container
      # ../extras:/repo/extras
    entrypoint: /bin/bash
    command: -lc "altivec-chooser"
