# Altivec Intelligence - SingleScreen (iPhone)
APP_NAME = SingleScreen
SOURCES = main.m AppDelegate.m
INFO_PLIST = Info.plist

# Import common iPhone build engine
include ../../altivec_common_phone.mk
