# Altivec Intelligence - CURLphone (iPhone)
APP_NAME = CURLphone
SOURCES = main.m DownloadViewController.m CrossPlatform.m

ALTIVECCORE_REQUIRED = 1
ALTIVECCOCOA_REQUIRED = 1

include /altivec/altivec_common_phone.mk
