# Altivec Intelligence - CURLphone (iPhone)
APP_NAME = CURLphone
SOURCES = main.m DownloadViewController.m CrossPlatform.m
INFO_PLIST = Info.plist

LIBCURL_REQUIRED = 1

# Resource files
RESOURCES = $(wildcard Resources/*.png)

include ../../altivec_common_phone.mk
