# SingleWindow Makefile
# Powered by Altivec Intelligence Common Build System

# 1. Project Identity
APP_NAME = SingleWindow
SOURCES = main.m
RES_DIR = Resources
INFO_PLIST = Info.plist

# 2. Import the Common Build Engine
include ../../altivec_common_mac.mk
